travis:
  secure:
    BINSTAR_TOKEN: iVFz/XP1mNVX+LiJRExZbjX2gWbVXAfhZQcBoI0atkBM5TMWTKjuQ3mxcDpfJZ+WzzpOgFl6SfVWbmkXYMeRwfFUw7nM1oaQEYq3NMzuE5WsRdJPkl9ITHYyOi0MC+iRj9ZWZ2HP7SCfnxCUk3R5GoGpFvH57gL7gccRFyczY8CdWZdQoBLjCzLr0uWtIvTbbdq71qZrkgOy9uYi1/GPEXDERnc/h5oB1Y4wndx9W18lyH0zP4ikfz4hJJljHoug8gZTmFS9AeObpOSg0RSkNJfL/boAphvSeZ8s9r7qy1/ptkRWkEv/d7h2+OZW4j0zEhO4LE3HisbtC3sncFnRYFe/BWzvXi153Tjl5uXyerHCIuH/F0a0yovZC9aJbuTf5tMc3uht+bcO+xjR/atbgXkqQ0VuPkGSZVWDRVtV+4Nx7darsssySkY/0s5XaKGdwd1qhYU3gcun07qs5hotZUZwWprOF74JXWGM5gfJ/MAGvEBlYXQEVeQoD0xk6DihtsUptA2v8+gcrXYOJ2ZBd6CekY5mt37G5Nd1KGWBn62iVuzBllh90WSdImHjjAoSYb8JNO+BrwZyWqpk/wUHhd5/lkFS167z6wzaqp6NYNeADwpgczG83BE6O5m6gsz1VSxkpI8qtVAAqIfSVXhsAbJwigOa8KPf6Zzaaj4347o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
